spring.application.name=sharepointV2
server.port=8080

sharepoint.auth.url=https://accounts.accesscontrol.windows.net/80f3ea7d-0e29-4591-9f60-bc5201a91499/tokens/OAuth/2
sharepoint.site.url=https://grupometalsa.sharepoint.com/sites/fttstest
sharepoint.attachment.base.path=/sites/FTTSTest/FTTS_Attachment
sharepoint.purchase-orders.list=PurchaseOrders
sharepoint.sbu=23613
sharepoint.client.id=e963cfdc-6c56-495c-b43a-e2879981c892@80f3ea7d-0e29-4591-9f60-bc5201a91499
sharepoint.client.secret=V3NhOFF+aXJ6S2hvfkRsaWVtSVBBc0puZ3lWYnlta29xaE8ySmM2NQ==
sharepoint.resource=00000003-0000-0ff1-ce00-000000000000/grupometalsa.sharepoint.com@80f3ea7d-0e29-4591-9f60-bc5201a91499
